export const SYMBOLS = {
	Bot: Symbol('Bot'),
	Client: Symbol('Client'),
	Token: Symbol('Token'),
	MessageHandlers: Symbol('MessageHandlers'),
	StopwatchCreator: Symbol('StopwatchCreator'),
	YtdlCreator: Symbol('YtdlCreator'),
	PredicateHelper: Symbol('PredicateHelper'),
	MessageRunner: Symbol('MessageRunner'),
	ErrorLogger: Symbol('ErrorLogger'),
	DbPool: Symbol('DbPool'),
	WATODatabase: Symbol('WATODatabase'),
	PingMessageHandler: Symbol('PingMessageHandler'),
	PlayYoutubeUrlMessageHandler: Symbol('PlayYoutubeUrlMessageHandler'),
	PauseMediaMessageHandler: Symbol('PauseMediaMessageHandler'),
	ResumeMediaMessageHandler: Symbol('ResumeMediaMessageHandler'),
	StopMediaMessageHandler: Symbol('StopMediaMessageHandler'),
	WATOChallengeMessageHandler: Symbol('WATOChallengeMessageHandler'),
	WATOResponseMessageHandler: Symbol('WATOResponseMessageHandler'),
	WATODeclineMessageHandler: Symbol('WATODeclineMessageHandler'),
	WATOBetMessageHandler: Symbol('WATOBetMessageHandler'),
	WATOHelpMessageHandler: Symbol('WATOHelpMessageHandler'),
	VoiceChannelService: Symbol('VoiceChannelService'),
	WatoHelperService: Symbol('WatoHelperService')
};
