name: Deploy Docker Compose

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: self-hosted
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Stop existing containers
        run: |
          docker compose down

      - name: Build and Start new containers
        env:
          PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
          LOG_LEVEL: ${{ vars.LOG_LEVEL }}
          DISCORD_BOT_TOKEN: ${{secrets.DISCORD_BOT_TOKEN}}
          LLM_URL: ${{secrets.LLM_URL}}
          DEZGO_TOKEN: ${{secrets.DEZGO_TOKEN}}
          POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          POSTGRES_DB: ${{vars.POSTGRES_DB}}
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          POSTGRES_HOST: ${{vars.POSTGRES_HOST}}

        run: |
          docker compose up --build -d

      - name: cleanup
        run : |
          docker image prune -f