name: Deploy Docker Compose

on:
  push:
    branches:
      - "main"
      - "fix"

jobs:
  deploy:
    runs-on: self-hosted
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: main

      - name: Stop existing containers
        run: |
          docker compose down >> /dev/null

      - name: Build and Start new containers
        env:
          PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
          LOG_LEVEL: ${{ vars.LOG_LEVEL }}
          DISCORD_BOT_TOKEN: ${{secrets.DISCORD_BOT_TOKEN}}
          LLM_URL: ${{secrets.LLM_URL}}
          DEZGO_TOKEN: ${{secrets.DEZGO_TOKEN}}
          POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          POSTGRES_DB: ${{secrets.POSTGRES_DB}}
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}

        run: |
          docker compose up --build hammy -d

      - name: cleanup
        run : |
          docker image prune -f